default: &default
  adapter: postgresql
  timeout: 5000
  username: FluffFox
  variables:
    statement_timeout: 10000

development:
  <<: *default
  database: FluffFox_development
  host: postgres
  pool: 5

test:
  <<: *default
  database: FluffFox_test
  host: postgres
  pool: 5

<% if Rails.env.production? %>
production:
  <<: *default
  database: FluffFox
  password: <%= ENV.fetch("DB_PASSWORD") %>
  host: <%= ENV.fetch("DB_HOST") %>
  port: <%= ENV.fetch("DB_PORT") %>
  pool: <%= Sidekiq.server? ? ENV.fetch("DB_WORKER_POOL_SIZE") : ENV.fetch("DB_POOL_SIZE") %>
<% end %>
